version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/docker/mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  client:
    image: aljithkjo2/workflo-client:latest
    container_name: workflo-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    image: aljithkjo2/workflo-server:latest
    container_name: workflo-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      MONGO_URL: mongodb://root:password@localhost:27017/workflo?authSource=admin
      SESSION_SECRET: 'secret'
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local